---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nginxhello
  namespace: default
spec:
  imageRepositoryRef:
    name: nginxhello
  policy:
    semver:
      range: '>=1.20.x'

